apiVersion: v1
kind: Service
metadata:
  name: ai-dps-web-svc
  namespace: ai-ml-dps
  labels:
    run: dps-web
spec:
  type: NodePort
  ports:
    - port: 80
      targetPort: 80
      nodePort:
  selector:
    run: dps-web