apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: ai-dps-web
  namespace: ai-ml-dps
spec:
  selector:
  template:
    metadata:
      labels:
        run: dps-web
    spec:
      containers:
        - image: harbor.aipo.lenovo.com/ai-ml-dps/dps_web:$version
          imagePullPolicy: IfNotPresent
          name: dps-web
          ports:
            - containerPort: 80
              protocol: TCP
          resources: {}