apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: po-ams-web
  namespace: po-ams
spec:
  selector:
  template:
    metadata:
      labels:
        run: po-ams-web
    spec:
      containers:
        - image: harbor.aipo.lenovo.com/po-ams/po-ams-web:$version
          imagePullPolicy: IfNotPresent
          name: po-ams-web
          ports:
            - containerPort: 80
              protocol: TCP
          resources: {}