apiVersion: v1
kind: Service
metadata:
  name: po-ams-web-svc
  namespace: po-ams
  labels:
    run: po-ams-web
spec:
  type: NodePort
  ports:
    - port: 80
      targetPort: 80
      nodePort:
  selector:
    run: po-ams-web