apiVersion: v1
data:
  mysqld.cnf: |-
    [mysqld]
    pid-file        = /var/run/mysqld/mysqld.pid
    socket          = /var/run/mysqld/mysqld.sock
    datadir         = /var/lib/mysql
    lower_case_table_names=1
kind: ConfigMap
metadata:
  name: po-ams-cm-mysql
  namespace: po-ams