kind: ConfigMap
apiVersion: v1
metadata:
  name: po-ams-redis-cm
  namespace: po-ams
  labels:
    app: redis
data:
  redis.conf: |
    dir /data
    port 6379
    bind 0.0.0.0
    appendonly yes
    protected-mode no
    requirepass po.ams.redis123456
    pidfile /data/redis-6379.pid