apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: po-ams-ser
  namespace: po-ams
spec:
  selector:
  template:
    metadata:
      labels:
        run: po-ams-ser
    spec:
      containers:
        - image: harbor.aipo.lenovo.com/po-ams/po-ams-ser:$version
          imagePullPolicy: IfNotPresent
          name: po-ams-ser
          ports:
            - containerPort: $version0
              protocol: TCP
          resources: {}