apiVersion: v1
kind: Service
metadata:
  name: po-ams-ser-svc
  namespace: po-ams
  labels:
    run: po-ams-ser
spec:
  type: NodePort
  ports:
    - port: 80
      targetPort: 80
  selector:
    run: po-ams-ser