apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: smartpack-ser
  namespace: smartdata
spec:
  selector:
  template:
    metadata:
      labels:
        run: smartpack-ser
    spec:
      containers:
        - image: harbor.aipo.lenovo.com/smartdata/smartpack-ser:$version
          imagePullPolicy: IfNotPresent
          name: smartpack-ser
          ports:
            - containerPort: 8080
              protocol: TCP
          resources: {}